steps:
  # until the db migration step is finished
  # https://cloud.google.com/sql/docs/postgres/sql-proxy
  - id: proxy
    name: gcr.io/cloudsql-docker/gce-proxy
    entrypoint: sh
    args:
      - '-c'
      - '/cloud_sql_proxy -dir=/cloudsql -instances=library-checker-project:asia-northeast1:library-checker-sql & while [ ! -f /cloudsql/stop ]; do sleep 2; done'
    waitFor: ['-']
    volumes:
      - name: db
        path: /cloudsql

  - id: generate_and_deploy
    name: gcr.io/library-checker-project/library-checker-problem-env
    entrypoint: sh
    args:
      - '-c'
      - './generate.py problems.toml && ./deploy.py && touch /cloudsql/stop'
    env: ['POSTGRE_HOST=127.0.0.1', 'POSTGRE_PASS=$_PG_PASS']
    volumes:
      - name: db
        path: /cloudsql

timeout: 1800s
