steps:
- name: gcr.io/develop-156705/library-checker-problem-env
  args: ['./generate.py', 'problems.toml']


# kind: pipeline
# name: default

# steps:
# - name: compiletest_clang
#   image: gcr.io/develop-156705/library-checker-problem-env
#   commands:
#     - ./generate.py problems.toml --compileonly
#   environment:
#     CXX: clang++
#     CXXFLAGS: -std=c++14 -stdlib=libc++ -Wall -Wextra

# - name: generate
#   image: gcr.io/develop-156705/library-checker-problem-env
#   commands:
#     - ./generate.py problems.toml
#   depend_on: [buildtest_clang]

# - name: deploy
#   image: gcr.io/develop-156705/library-checker-problem-env
#   commands:
#     - ./deploy.py
#   environment:
#     POSTGRE_HOST:
#       from_secret: pg_host
#     POSTGRE_PORT:
#       from_secret: pg_port
#     POSTGRE_USER:
#       from_secret: pg_user
#     POSTGRE_PASS:
#       from_secret: pg_pass
#   depend_on: [generate]
#   when:
#     branch:
#     - master
#     event:
#     - push
    
# image_pull_secrets:
# - google_credentials
