title = 'Dynamic Tree Vertex Add Path Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/223"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "long-path-decomposition_killer.cpp"
    number = 1


[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_AND_Q_MIN = 1
    N_AND_Q_MAX = 200_000
    A_AND_X_MIN = 0
    A_AND_X_MAX = 1_000_000_000
