solution = "correct.cpp"
verify = "verify.cpp"
timelimit = 5.0

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "cycle_unsat.cpp"
    number = 2

[[solutions]]
    name = 'correct.cpp'
