FROM python:3.6-alpine3.9

RUN apk add g++
#RUN apt-get -y upgrade
#RUN apt-get install -y postgresql libpq-dev python3 python3-pip g++ clang libc++-dev libc++abi-dev
#RUN apt-get clean

#RUN pip3 install --upgrade pip
#RUN pip3 install termcolor toml psycopg2 markdown
