name: Diff

on:
  push:
    branches:
      - master
      - refactor/test
  pull_request:
  workflow_dispatch:

jobs:
  gcc-ubuntu-diffrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt

      - name: Restore versions.json
        uses: actions/cache/restore@v3
        with:
          path: versions.json
          key: ${{ runner.os }}-versions-cache-

      - name: Run generate.py on gcc
        run: |
          ulimit -s unlimited
          ./generate_test.py TestGenerateAll
        env:
          ENABLE_GENERATE_TEST: 1
          VERSIONS_CACHE_PATH: versions.json

      - name: Save versions.json
        uses: actions/cache/save@v3
        with:
          path: versions.json
          key: ${{ runner.os }}-versions-cache-${{ hashFiles('versions.json') }}
